services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "443:443"
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/index.js:/app/index.js
      - ./frontend:/app/frontend
      - ./certs:/app/certs
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/tpdb
    depends_on:
      - mongo
    command: sh -c "npm install && node index.js"

volumes:
  mongo-data: