services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/index.js:/app/index.js
      - ./frontend:/app/frontend
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/tpdb
    depends_on:
      - mongo
    command: sh -c "npm install && node index.js"

  caddy:
      image: caddy:alpine
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"  # HTTP/3
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - app
      restart: unless-stopped

volumes:
  mongo-data:
  caddy_data:
  caddy_config: